INVITML1.FILE: INVITML1-Inventory_Item_ID.LF INVITM.FILE
INVITM.FILE: INVITM-Inventory_items.PF FIELDREF.FILE
INV200D.FILE: INV200D-Work_with_Inventory_Item.DSPF INVITM.FILE HSTDEF.FILE
HSTDEF.FILE: HSTDEF-HST_definition.PF FIELDREF.FILE
INVITML2.FILE: INVITML2-Inventory_Item_Desc_ID.LF INVITM.FILE